

    public enum Keyword
    {
        If, 
        Else, 
        Try, 
        Catch, 
        DataType, 
        Operator, 
        Visibility,
        Costant, 
        Class,
        Name, 
        Variable, 
        Function,
        OpenPar,
        ClosePar,
        OpenBracket, 
        CloseBracket, 
        OpenAngle, 
        CloseAngle,
        Equals, 
        Comma, 
        Switch, 
        Semicolon, 
        Command, 
        Return,
        Unknown,
        Newline,
        Comparison, 
        Expression,
        Assignment,
        Start, End,
    }
